worker_processes 1;

error_log /infoq/nginx/log/error.log warn;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    keepalive_requests 100000;
    client_max_body_size 100m;
    client_header_buffer_size 32k;
    client_body_buffer_size 512k;
    gzip_static on;
    server_tokens off;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /infoq/nginx/log/access.log main;

    upstream backend_server {
        server 127.0.0.1:9090;
    }

    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name _;

        ssl_certificate /infoq/nginx/cert/infoq.local.crt;
        ssl_certificate_key /infoq/nginx/cert/infoq.local.key;
        ssl_session_timeout 10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers off;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location ~ ^(/[^/]*)?/actuator.*(/.*)?$ {
            return 403;
        }

        location = / {
            return 302 /vue/;
        }

        location = /vue {
            return 302 /vue/;
        }

        location = /react {
            return 302 /react/;
        }

        location ^~ /vue/ {
            root /infoq/nginx/html;
            try_files $uri $uri/ /vue/index.html;
        }

        location ^~ /react/ {
            root /infoq/nginx/html;
            try_files $uri $uri/ /react/index.html;
        }

        location /prod-api/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400s;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;
            proxy_cache off;
            proxy_pass http://backend_server/;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
